# ASP.NET Core
trigger:
- main

pool:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/.csproj'
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
